exports.seed = async function (knex) {
  await knex.raw('delete from countries');
  await knex.batchInsert('countries', [
    { "id": "ABW", "iso2code": "AW", "name": "Aruba", "capital_city": "Oranjestad", "longitude": "-70.0167", "latitude": "12.5167" },
    { "id": "AFG", "iso2code": "AF", "name": "Afghanistan", "capital_city": "Kabul", "longitude": "69.1761", "latitude": "34.5228" },
    { "id": "AFR", "iso2code": "A9", "name": "Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "AGO", "iso2code": "AO", "name": "Angola", "capital_city": "Luanda", "longitude": "13.242", "latitude": "-8.81155" },
    { "id": "ALB", "iso2code": "AL", "name": "Albania", "capital_city": "Tirane", "longitude": "19.8172", "latitude": "41.3317" },
    { "id": "AND", "iso2code": "AD", "name": "Andorra", "capital_city": "Andorra la Vella", "longitude": "1.5218", "latitude": "42.5075" },
    { "id": "ANR", "iso2code": "L5", "name": "Andean Region", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "ARB", "iso2code": "1A", "name": "Arab World", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "ARE", "iso2code": "AE", "name": "United Arab Emirates", "capital_city": "Abu Dhabi", "longitude": "54.3705", "latitude": "24.4764" },
    { "id": "ARG", "iso2code": "AR", "name": "Argentina", "capital_city": "Buenos Aires", "longitude": "-58.4173", "latitude": "-34.6118" },
    { "id": "ARM", "iso2code": "AM", "name": "Armenia", "capital_city": "Yerevan", "longitude": "44.509", "latitude": "40.1596" },
    { "id": "ASM", "iso2code": "AS", "name": "American Samoa", "capital_city": "Pago Pago", "longitude": "-170.691", "latitude": "-14.2846" },
    { "id": "ATG", "iso2code": "AG", "name": "Antigua and Barbuda", "capital_city": "Saint John's", "longitude": "-61.8456", "latitude": "17.1175" },
    { "id": "AUS", "iso2code": "AU", "name": "Australia", "capital_city": "Canberra", "longitude": "149.129", "latitude": "-35.282" },
    { "id": "AUT", "iso2code": "AT", "name": "Austria", "capital_city": "Vienna", "longitude": "16.3798", "latitude": "48.2201" },
    { "id": "AZE", "iso2code": "AZ", "name": "Azerbaijan", "capital_city": "Baku", "longitude": "49.8932", "latitude": "40.3834" },
    { "id": "BDI", "iso2code": "BI", "name": "Burundi", "capital_city": "Bujumbura", "longitude": "29.3639", "latitude": "-3.3784" },
    { "id": "BEA", "iso2code": "B4", "name": "East Asia & Pacific (IBRD-only countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "BEC", "iso2code": "B7", "name": "Europe & Central Asia (IBRD-only countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "BEL", "iso2code": "BE", "name": "Belgium", "capital_city": "Brussels", "longitude": "4.36761", "latitude": "50.8371" },
    { "id": "BEN", "iso2code": "BJ", "name": "Benin", "capital_city": "Porto-Novo", "longitude": "2.6323", "latitude": "6.4779" },
    { "id": "BFA", "iso2code": "BF", "name": "Burkina Faso", "capital_city": "Ouagadougou", "longitude": "-1.53395", "latitude": "12.3605" },
    { "id": "BGD", "iso2code": "BD", "name": "Bangladesh", "capital_city": "Dhaka", "longitude": "90.4113", "latitude": "23.7055" },
    { "id": "BGR", "iso2code": "BG", "name": "Bulgaria", "capital_city": "Sofia", "longitude": "23.3238", "latitude": "42.7105" },
    { "id": "BHI", "iso2code": "B1", "name": "IBRD countries classified as high income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "BHR", "iso2code": "BH", "name": "Bahrain", "capital_city": "Manama", "longitude": "50.5354", "latitude": "26.1921" },
    { "id": "BHS", "iso2code": "BS", "name": "Bahamas, The", "capital_city": "Nassau", "longitude": "-77.339", "latitude": "25.0661" },
    { "id": "BIH", "iso2code": "BA", "name": "Bosnia and Herzegovina", "capital_city": "Sarajevo", "longitude": "18.4214", "latitude": "43.8607" },
    { "id": "BLA", "iso2code": "B2", "name": "Latin America & the Caribbean (IBRD-only countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "BLR", "iso2code": "BY", "name": "Belarus", "capital_city": "Minsk", "longitude": "27.5766", "latitude": "53.9678" },
    { "id": "BLZ", "iso2code": "BZ", "name": "Belize", "capital_city": "Belmopan", "longitude": "-88.7713", "latitude": "17.2534" },
    { "id": "BMN", "iso2code": "B3", "name": "Middle East & North Africa (IBRD-only countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "BMU", "iso2code": "BM", "name": "Bermuda", "capital_city": "Hamilton", "longitude": "-64.706", "latitude": "32.3293" },
    { "id": "BOL", "iso2code": "BO", "name": "Bolivia", "capital_city": "La Paz", "longitude": "-66.1936", "latitude": "-13.9908" },
    { "id": "BRA", "iso2code": "BR", "name": "Brazil", "capital_city": "Brasilia", "longitude": "-47.9292", "latitude": "-15.7801" },
    { "id": "BRB", "iso2code": "BB", "name": "Barbados", "capital_city": "Bridgetown", "longitude": "-59.6105", "latitude": "13.0935" },
    { "id": "BRN", "iso2code": "BN", "name": "Brunei Darussalam", "capital_city": "Bandar Seri Begawan", "longitude": "114.946", "latitude": "4.94199" },
    { "id": "BSS", "iso2code": "B6", "name": "Sub-Saharan Africa (IBRD-only countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "BTN", "iso2code": "BT", "name": "Bhutan", "capital_city": "Thimphu", "longitude": "89.6177", "latitude": "27.5768" },
    { "id": "BWA", "iso2code": "BW", "name": "Botswana", "capital_city": "Gaborone", "longitude": "25.9201", "latitude": "-24.6544" },
    { "id": "CAA", "iso2code": "C9", "name": "Sub-Saharan Africa (IFC classification)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CAF", "iso2code": "CF", "name": "Central African Republic", "capital_city": "Bangui", "longitude": "21.6407", "latitude": "5.63056" },
    { "id": "CAN", "iso2code": "CA", "name": "Canada", "capital_city": "Ottawa", "longitude": "-75.6919", "latitude": "45.4215" },
    { "id": "CEA", "iso2code": "C4", "name": "East Asia and the Pacific (IFC classification)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CEB", "iso2code": "B8", "name": "Central Europe and the Baltics", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CEU", "iso2code": "C5", "name": "Europe and Central Asia (IFC classification)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CHE", "iso2code": "CH", "name": "Switzerland", "capital_city": "Bern", "longitude": "7.44821", "latitude": "46.948" },
    { "id": "CHI", "iso2code": "JG", "name": "Channel Islands", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CHL", "iso2code": "CL", "name": "Chile", "capital_city": "Santiago", "longitude": "-70.6475", "latitude": "-33.475" },
    { "id": "CHN", "iso2code": "CN", "name": "China", "capital_city": "Beijing", "longitude": "116.286", "latitude": "40.0495" },
    { "id": "CIV", "iso2code": "CI", "name": "Cote d'Ivoire", "capital_city": "Yamoussoukro", "longitude": "-4.0305", "latitude": "5.332" },
    { "id": "CLA", "iso2code": "C6", "name": "Latin America and the Caribbean (IFC classification)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CME", "iso2code": "C7", "name": "Middle East and North Africa (IFC classification)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CMR", "iso2code": "CM", "name": "Cameroon", "capital_city": "Yaounde", "longitude": "11.5174", "latitude": "3.8721" },
    { "id": "COD", "iso2code": "CD", "name": "Congo, Dem. Rep.", "capital_city": "Kinshasa", "longitude": "15.3222", "latitude": "-4.325" },
    { "id": "COG", "iso2code": "CG", "name": "Congo, Rep.", "capital_city": "Brazzaville", "longitude": "15.2662", "latitude": "-4.2767" },
    { "id": "COL", "iso2code": "CO", "name": "Colombia", "capital_city": "Bogota", "longitude": "-74.082", "latitude": "4.60987" },
    { "id": "COM", "iso2code": "KM", "name": "Comoros", "capital_city": "Moroni", "longitude": "43.2418", "latitude": "-11.6986" },
    { "id": "CPV", "iso2code": "CV", "name": "Cabo Verde", "capital_city": "Praia", "longitude": "-23.5087", "latitude": "14.9218" },
    { "id": "CRI", "iso2code": "CR", "name": "Costa Rica", "capital_city": "San Jose", "longitude": "-84.0089", "latitude": "9.63701" },
    { "id": "CSA", "iso2code": "C8", "name": "South Asia (IFC classification)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CSS", "iso2code": "S3", "name": "Caribbean small states", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "CUB", "iso2code": "CU", "name": "Cuba", "capital_city": "Havana", "longitude": "-82.3667", "latitude": "23.1333" },
    { "id": "CUW", "iso2code": "CW", "name": "Curacao", "capital_city": "Willemstad", "longitude": "", "latitude": "" },
    { "id": "CYM", "iso2code": "KY", "name": "Cayman Islands", "capital_city": "George Town", "longitude": "-81.3857", "latitude": "19.3022" },
    { "id": "CYP", "iso2code": "CY", "name": "Cyprus", "capital_city": "Nicosia", "longitude": "33.3736", "latitude": "35.1676" },
    { "id": "CZE", "iso2code": "CZ", "name": "Czech Republic", "capital_city": "Prague", "longitude": "14.4205", "latitude": "50.0878" },
    { "id": "DEA", "iso2code": "D4", "name": "East Asia & Pacific (IDA-eligible countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DEC", "iso2code": "D7", "name": "Europe & Central Asia (IDA-eligible countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DEU", "iso2code": "DE", "name": "Germany", "capital_city": "Berlin", "longitude": "13.4115", "latitude": "52.5235" },
    { "id": "DFS", "iso2code": "D8", "name": "IDA countries classified as Fragile Situations", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DJI", "iso2code": "DJ", "name": "Djibouti", "capital_city": "Djibouti", "longitude": "43.1425", "latitude": "11.5806" },
    { "id": "DLA", "iso2code": "D2", "name": "Latin America & the Caribbean (IDA-eligible countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DMA", "iso2code": "DM", "name": "Dominica", "capital_city": "Roseau", "longitude": "-61.39", "latitude": "15.2976" },
    { "id": "DMN", "iso2code": "D3", "name": "Middle East & North Africa (IDA-eligible countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DNF", "iso2code": "D9", "name": "IDA countries not classified as Fragile Situations", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DNK", "iso2code": "DK", "name": "Denmark", "capital_city": "Copenhagen", "longitude": "12.5681", "latitude": "55.6763" },
    { "id": "DNS", "iso2code": "N6", "name": "IDA countries in Sub-Saharan Africa not classified as fragile situations ", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DOM", "iso2code": "DO", "name": "Dominican Republic", "capital_city": "Santo Domingo", "longitude": "-69.8908", "latitude": "18.479" },
    { "id": "DSA", "iso2code": "D5", "name": "South Asia (IDA-eligible countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DSF", "iso2code": "F6", "name": "IDA countries in Sub-Saharan Africa classified as fragile situations ", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DSS", "iso2code": "D6", "name": "Sub-Saharan Africa (IDA-eligible countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DXS", "iso2code": "6D", "name": "IDA total, excluding Sub-Saharan Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "DZA", "iso2code": "DZ", "name": "Algeria", "capital_city": "Algiers", "longitude": "3.05097", "latitude": "36.7397" },
    { "id": "EAP", "iso2code": "4E", "name": "East Asia & Pacific (excluding high income)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "EAR", "iso2code": "V2", "name": "Early-demographic dividend", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "EAS", "iso2code": "Z4", "name": "East Asia & Pacific", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "ECA", "iso2code": "7E", "name": "Europe & Central Asia (excluding high income)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "ECS", "iso2code": "Z7", "name": "Europe & Central Asia", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "ECU", "iso2code": "EC", "name": "Ecuador", "capital_city": "Quito", "longitude": "-78.5243", "latitude": "-0.229498" },
    { "id": "EGY", "iso2code": "EG", "name": "Egypt, Arab Rep.", "capital_city": "Cairo", "longitude": "31.2461", "latitude": "30.0982" },
    { "id": "EMU", "iso2code": "XC", "name": "Euro area", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "ERI", "iso2code": "ER", "name": "Eritrea", "capital_city": "Asmara", "longitude": "38.9183", "latitude": "15.3315" },
    { "id": "ESP", "iso2code": "ES", "name": "Spain", "capital_city": "Madrid", "longitude": "-3.70327", "latitude": "40.4167" },
    { "id": "EST", "iso2code": "EE", "name": "Estonia", "capital_city": "Tallinn", "longitude": "24.7586", "latitude": "59.4392" },
    { "id": "ETH", "iso2code": "ET", "name": "Ethiopia", "capital_city": "Addis Ababa", "longitude": "38.7468", "latitude": "9.02274" },
    { "id": "EUU", "iso2code": "EU", "name": "European Union", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "FCS", "iso2code": "F1", "name": "Fragile and conflict affected situations", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "FIN", "iso2code": "FI", "name": "Finland", "capital_city": "Helsinki", "longitude": "24.9525", "latitude": "60.1608" },
    { "id": "FJI", "iso2code": "FJ", "name": "Fiji", "capital_city": "Suva", "longitude": "178.399", "latitude": "-18.1149" },
    { "id": "FRA", "iso2code": "FR", "name": "France", "capital_city": "Paris", "longitude": "2.35097", "latitude": "48.8566" },
    { "id": "FRO", "iso2code": "FO", "name": "Faroe Islands", "capital_city": "Torshavn", "longitude": "-6.91181", "latitude": "61.8926" },
    { "id": "FSM", "iso2code": "FM", "name": "Micronesia, Fed. Sts.", "capital_city": "Palikir", "longitude": "158.185", "latitude": "6.91771" },
    { "id": "FXS", "iso2code": "6F", "name": "IDA countries classified as fragile situations, excluding Sub-Saharan Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "GAB", "iso2code": "GA", "name": "Gabon", "capital_city": "Libreville", "longitude": "9.45162", "latitude": "0.38832" },
    { "id": "GBR", "iso2code": "GB", "name": "United Kingdom", "capital_city": "London", "longitude": "-0.126236", "latitude": "51.5002" },
    { "id": "GEO", "iso2code": "GE", "name": "Georgia", "capital_city": "Tbilisi", "longitude": "44.793", "latitude": "41.71" },
    { "id": "GHA", "iso2code": "GH", "name": "Ghana", "capital_city": "Accra", "longitude": "-0.20795", "latitude": "5.57045" },
    { "id": "GIB", "iso2code": "GI", "name": "Gibraltar", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "GIN", "iso2code": "GN", "name": "Guinea", "capital_city": "Conakry", "longitude": "-13.7", "latitude": "9.51667" },
    { "id": "GMB", "iso2code": "GM", "name": "Gambia, The", "capital_city": "Banjul", "longitude": "-16.5885", "latitude": "13.4495" },
    { "id": "GNB", "iso2code": "GW", "name": "Guinea-Bissau", "capital_city": "Bissau", "longitude": "-15.1804", "latitude": "11.8037" },
    { "id": "GNQ", "iso2code": "GQ", "name": "Equatorial Guinea", "capital_city": "Malabo", "longitude": "8.7741", "latitude": "3.7523" },
    { "id": "GRC", "iso2code": "GR", "name": "Greece", "capital_city": "Athens", "longitude": "23.7166", "latitude": "37.9792" },
    { "id": "GRD", "iso2code": "GD", "name": "Grenada", "capital_city": "Saint George's", "longitude": "-61.7449", "latitude": "12.0653" },
    { "id": "GRL", "iso2code": "GL", "name": "Greenland", "capital_city": "Nuuk", "longitude": "-51.7214", "latitude": "64.1836" },
    { "id": "GTM", "iso2code": "GT", "name": "Guatemala", "capital_city": "Guatemala City", "longitude": "-90.5328", "latitude": "14.6248" },
    { "id": "GUM", "iso2code": "GU", "name": "Guam", "capital_city": "Agana", "longitude": "144.794", "latitude": "13.4443" },
    { "id": "GUY", "iso2code": "GY", "name": "Guyana", "capital_city": "Georgetown", "longitude": "-58.1548", "latitude": "6.80461" },
    { "id": "HIC", "iso2code": "XD", "name": "High income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "HKG", "iso2code": "HK", "name": "Hong Kong SAR, China", "capital_city": "", "longitude": "114.109", "latitude": "22.3964" },
    { "id": "HND", "iso2code": "HN", "name": "Honduras", "capital_city": "Tegucigalpa", "longitude": "-87.4667", "latitude": "15.1333" },
    { "id": "HPC", "iso2code": "XE", "name": "Heavily indebted poor countries (HIPC)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "HRV", "iso2code": "HR", "name": "Croatia", "capital_city": "Zagreb", "longitude": "15.9614", "latitude": "45.8069" },
    { "id": "HTI", "iso2code": "HT", "name": "Haiti", "capital_city": "Port-au-Prince", "longitude": "-72.3288", "latitude": "18.5392" },
    { "id": "HUN", "iso2code": "HU", "name": "Hungary", "capital_city": "Budapest", "longitude": "19.0408", "latitude": "47.4984" },
    { "id": "IBB", "iso2code": "ZB", "name": "IBRD, including blend", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IBD", "iso2code": "XF", "name": "IBRD only", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IBT", "iso2code": "ZT", "name": "IDA & IBRD total", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IDA", "iso2code": "XG", "name": "IDA total", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IDB", "iso2code": "XH", "name": "IDA blend", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IDN", "iso2code": "ID", "name": "Indonesia", "capital_city": "Jakarta", "longitude": "106.83", "latitude": "-6.19752" },
    { "id": "IDX", "iso2code": "XI", "name": "IDA only", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IMN", "iso2code": "IM", "name": "Isle of Man", "capital_city": "Douglas", "longitude": "-4.47928", "latitude": "54.1509" },
    { "id": "IND", "iso2code": "IN", "name": "India", "capital_city": "New Delhi", "longitude": "77.225", "latitude": "28.6353" },
    { "id": "INX", "iso2code": "XY", "name": "Not classified", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "IRL", "iso2code": "IE", "name": "Ireland", "capital_city": "Dublin", "longitude": "-6.26749", "latitude": "53.3441" },
    { "id": "IRN", "iso2code": "IR", "name": "Iran, Islamic Rep.", "capital_city": "Tehran", "longitude": "51.4447", "latitude": "35.6878" },
    { "id": "IRQ", "iso2code": "IQ", "name": "Iraq", "capital_city": "Baghdad", "longitude": "44.394", "latitude": "33.3302" },
    { "id": "ISL", "iso2code": "IS", "name": "Iceland", "capital_city": "Reykjavik", "longitude": "-21.8952", "latitude": "64.1353" },
    { "id": "ISR", "iso2code": "IL", "name": "Israel", "capital_city": "", "longitude": "35.2035", "latitude": "31.7717" },
    { "id": "ITA", "iso2code": "IT", "name": "Italy", "capital_city": "Rome", "longitude": "12.4823", "latitude": "41.8955" },
    { "id": "JAM", "iso2code": "JM", "name": "Jamaica", "capital_city": "Kingston", "longitude": "-76.792", "latitude": "17.9927" },
    { "id": "JOR", "iso2code": "JO", "name": "Jordan", "capital_city": "Amman", "longitude": "35.9263", "latitude": "31.9497" },
    { "id": "JPN", "iso2code": "JP", "name": "Japan", "capital_city": "Tokyo", "longitude": "139.77", "latitude": "35.67" },
    { "id": "KAZ", "iso2code": "KZ", "name": "Kazakhstan", "capital_city": "Astana", "longitude": "71.4382", "latitude": "51.1879" },
    { "id": "KEN", "iso2code": "KE", "name": "Kenya", "capital_city": "Nairobi", "longitude": "36.8126", "latitude": "-1.27975" },
    { "id": "KGZ", "iso2code": "KG", "name": "Kyrgyz Republic", "capital_city": "Bishkek", "longitude": "74.6057", "latitude": "42.8851" },
    { "id": "KHM", "iso2code": "KH", "name": "Cambodia", "capital_city": "Phnom Penh", "longitude": "104.874", "latitude": "11.5556" },
    { "id": "KIR", "iso2code": "KI", "name": "Kiribati", "capital_city": "Tarawa", "longitude": "172.979", "latitude": "1.32905" },
    { "id": "KNA", "iso2code": "KN", "name": "St. Kitts and Nevis", "capital_city": "Basseterre", "longitude": "-62.7309", "latitude": "17.3" },
    { "id": "KOR", "iso2code": "KR", "name": "Korea, Rep.", "capital_city": "Seoul", "longitude": "126.957", "latitude": "37.5323" },
    { "id": "KWT", "iso2code": "KW", "name": "Kuwait", "capital_city": "Kuwait City", "longitude": "47.9824", "latitude": "29.3721" },
    { "id": "LAC", "iso2code": "XJ", "name": "Latin America & Caribbean (excluding high income)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LAO", "iso2code": "LA", "name": "Lao PDR", "capital_city": "Vientiane", "longitude": "102.177", "latitude": "18.5826" },
    { "id": "LBN", "iso2code": "LB", "name": "Lebanon", "capital_city": "Beirut", "longitude": "35.5134", "latitude": "33.8872" },
    { "id": "LBR", "iso2code": "LR", "name": "Liberia", "capital_city": "Monrovia", "longitude": "-10.7957", "latitude": "6.30039" },
    { "id": "LBY", "iso2code": "LY", "name": "Libya", "capital_city": "Tripoli", "longitude": "13.1072", "latitude": "32.8578" },
    { "id": "LCA", "iso2code": "LC", "name": "St. Lucia", "capital_city": "Castries", "longitude": "-60.9832", "latitude": "14" },
    { "id": "LCN", "iso2code": "ZJ", "name": "Latin America & Caribbean ", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LCR", "iso2code": "L4", "name": "Latin America and the Caribbean", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LDC", "iso2code": "XL", "name": "Least developed countries: UN classification", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LIC", "iso2code": "XM", "name": "Low income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LIE", "iso2code": "LI", "name": "Liechtenstein", "capital_city": "Vaduz", "longitude": "9.52148", "latitude": "47.1411" },
    { "id": "LKA", "iso2code": "LK", "name": "Sri Lanka", "capital_city": "Colombo", "longitude": "79.8528", "latitude": "6.92148" },
    { "id": "LMC", "iso2code": "XN", "name": "Lower middle income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LMY", "iso2code": "XO", "name": "Low & middle income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LSO", "iso2code": "LS", "name": "Lesotho", "capital_city": "Maseru", "longitude": "27.7167", "latitude": "-29.5208" },
    { "id": "LTE", "iso2code": "V3", "name": "Late-demographic dividend", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "LTU", "iso2code": "LT", "name": "Lithuania", "capital_city": "Vilnius", "longitude": "25.2799", "latitude": "54.6896" },
    { "id": "LUX", "iso2code": "LU", "name": "Luxembourg", "capital_city": "Luxembourg", "longitude": "6.1296", "latitude": "49.61" },
    { "id": "LVA", "iso2code": "LV", "name": "Latvia", "capital_city": "Riga", "longitude": "24.1048", "latitude": "56.9465" },
    { "id": "MAC", "iso2code": "MO", "name": "Macao SAR, China", "capital_city": "", "longitude": "113.55", "latitude": "22.1667" },
    { "id": "MAF", "iso2code": "MF", "name": "St. Martin (French part)", "capital_city": "Marigot", "longitude": "", "latitude": "" },
    { "id": "MAR", "iso2code": "MA", "name": "Morocco", "capital_city": "Rabat", "longitude": "-6.8704", "latitude": "33.9905" },
    { "id": "MCA", "iso2code": "L6", "name": "Central America", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "MCO", "iso2code": "MC", "name": "Monaco", "capital_city": "Monaco", "longitude": "7.41891", "latitude": "43.7325" },
    { "id": "MDA", "iso2code": "MD", "name": "Moldova", "capital_city": "Chisinau", "longitude": "28.8497", "latitude": "47.0167" },
    { "id": "MDE", "iso2code": "M1", "name": "Middle East (developing only)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "MDG", "iso2code": "MG", "name": "Madagascar", "capital_city": "Antananarivo", "longitude": "45.7167", "latitude": "-20.4667" },
    { "id": "MDV", "iso2code": "MV", "name": "Maldives", "capital_city": "Male", "longitude": "73.5109", "latitude": "4.1742" },
    { "id": "MEA", "iso2code": "ZQ", "name": "Middle East & North Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "MEX", "iso2code": "MX", "name": "Mexico", "capital_city": "Mexico City", "longitude": "-99.1276", "latitude": "19.427" },
    { "id": "MHL", "iso2code": "MH", "name": "Marshall Islands", "capital_city": "Majuro", "longitude": "171.135", "latitude": "7.11046" },
    { "id": "MIC", "iso2code": "XP", "name": "Middle income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "MKD", "iso2code": "MK", "name": "North Macedonia", "capital_city": "Skopje", "longitude": "21.4361", "latitude": "42.0024" },
    { "id": "MLI", "iso2code": "ML", "name": "Mali", "capital_city": "Bamako", "longitude": "-7.50034", "latitude": "13.5667" },
    { "id": "MLT", "iso2code": "MT", "name": "Malta", "capital_city": "Valletta", "longitude": "14.5189", "latitude": "35.9042" },
    { "id": "MMR", "iso2code": "MM", "name": "Myanmar", "capital_city": "Naypyidaw", "longitude": "95.9562", "latitude": "21.914" },
    { "id": "MNA", "iso2code": "XQ", "name": "Middle East & North Africa (excluding high income)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "MNE", "iso2code": "ME", "name": "Montenegro", "capital_city": "Podgorica", "longitude": "19.2595", "latitude": "42.4602" },
    { "id": "MNG", "iso2code": "MN", "name": "Mongolia", "capital_city": "Ulaanbaatar", "longitude": "106.937", "latitude": "47.9129" },
    { "id": "MNP", "iso2code": "MP", "name": "Northern Mariana Islands", "capital_city": "Saipan", "longitude": "145.765", "latitude": "15.1935" },
    { "id": "MOZ", "iso2code": "MZ", "name": "Mozambique", "capital_city": "Maputo", "longitude": "32.5713", "latitude": "-25.9664" },
    { "id": "MRT", "iso2code": "MR", "name": "Mauritania", "capital_city": "Nouakchott", "longitude": "-15.9824", "latitude": "18.2367" },
    { "id": "MUS", "iso2code": "MU", "name": "Mauritius", "capital_city": "Port Louis", "longitude": "57.4977", "latitude": "-20.1605" },
    { "id": "MWI", "iso2code": "MW", "name": "Malawi", "capital_city": "Lilongwe", "longitude": "33.7703", "latitude": "-13.9899" },
    { "id": "MYS", "iso2code": "MY", "name": "Malaysia", "capital_city": "Kuala Lumpur", "longitude": "101.684", "latitude": "3.12433" },
    { "id": "NAC", "iso2code": "XU", "name": "North America", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "NAF", "iso2code": "M2", "name": "North Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "NAM", "iso2code": "NA", "name": "Namibia", "capital_city": "Windhoek", "longitude": "17.0931", "latitude": "-22.5648" },
    { "id": "NCL", "iso2code": "NC", "name": "New Caledonia", "capital_city": "Noum'ea", "longitude": "166.464", "latitude": "-22.2677" },
    { "id": "NER", "iso2code": "NE", "name": "Niger", "capital_city": "Niamey", "longitude": "2.1073", "latitude": "13.514" },
    { "id": "NGA", "iso2code": "NG", "name": "Nigeria", "capital_city": "Abuja", "longitude": "7.48906", "latitude": "9.05804" },
    { "id": "NIC", "iso2code": "NI", "name": "Nicaragua", "capital_city": "Managua", "longitude": "-86.2734", "latitude": "12.1475" },
    { "id": "NLD", "iso2code": "NL", "name": "Netherlands", "capital_city": "Amsterdam", "longitude": "4.89095", "latitude": "52.3738" },
    { "id": "NLS", "iso2code": "6L", "name": "Non-resource rich Sub-Saharan Africa countries, of which landlocked", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "NOR", "iso2code": "NO", "name": "Norway", "capital_city": "Oslo", "longitude": "10.7387", "latitude": "59.9138" },
    { "id": "NPL", "iso2code": "NP", "name": "Nepal", "capital_city": "Kathmandu", "longitude": "85.3157", "latitude": "27.6939" },
    { "id": "NRS", "iso2code": "6X", "name": "Non-resource rich Sub-Saharan Africa countries", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "NRU", "iso2code": "NR", "name": "Nauru", "capital_city": "Yaren District", "longitude": "166.920867", "latitude": "-0.5477" },
    { "id": "NXS", "iso2code": "6N", "name": "IDA countries not classified as fragile situations, excluding Sub-Saharan Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "NZL", "iso2code": "NZ", "name": "New Zealand", "capital_city": "Wellington", "longitude": "174.776", "latitude": "-41.2865" },
    { "id": "OED", "iso2code": "OE", "name": "OECD members", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "OMN", "iso2code": "OM", "name": "Oman", "capital_city": "Muscat", "longitude": "58.5874", "latitude": "23.6105" },
    { "id": "OSS", "iso2code": "S4", "name": "Other small states", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "PAK", "iso2code": "PK", "name": "Pakistan", "capital_city": "Islamabad", "longitude": "72.8", "latitude": "30.5167" },
    { "id": "PAN", "iso2code": "PA", "name": "Panama", "capital_city": "Panama City", "longitude": "-79.5188", "latitude": "8.99427" },
    { "id": "PER", "iso2code": "PE", "name": "Peru", "capital_city": "Lima", "longitude": "-77.0465", "latitude": "-12.0931" },
    { "id": "PHL", "iso2code": "PH", "name": "Philippines", "capital_city": "Manila", "longitude": "121.035", "latitude": "14.5515" },
    { "id": "PLW", "iso2code": "PW", "name": "Palau", "capital_city": "Koror", "longitude": "134.479", "latitude": "7.34194" },
    { "id": "PNG", "iso2code": "PG", "name": "Papua New Guinea", "capital_city": "Port Moresby", "longitude": "147.194", "latitude": "-9.47357" },
    { "id": "POL", "iso2code": "PL", "name": "Poland", "capital_city": "Warsaw", "longitude": "21.02", "latitude": "52.26" },
    { "id": "PRE", "iso2code": "V1", "name": "Pre-demographic dividend", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "PRI", "iso2code": "PR", "name": "Puerto Rico", "capital_city": "San Juan", "longitude": "-66", "latitude": "18.23" },
    { "id": "PRK", "iso2code": "KP", "name": "Korea, Dem. People’s Rep.", "capital_city": "Pyongyang", "longitude": "125.754", "latitude": "39.0319" },
    { "id": "PRT", "iso2code": "PT", "name": "Portugal", "capital_city": "Lisbon", "longitude": "-9.13552", "latitude": "38.7072" },
    { "id": "PRY", "iso2code": "PY", "name": "Paraguay", "capital_city": "Asuncion", "longitude": "-57.6362", "latitude": "-25.3005" },
    { "id": "PSE", "iso2code": "PS", "name": "West Bank and Gaza", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "PSS", "iso2code": "S2", "name": "Pacific island small states", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "PST", "iso2code": "V4", "name": "Post-demographic dividend", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "PYF", "iso2code": "PF", "name": "French Polynesia", "capital_city": "Papeete", "longitude": "-149.57", "latitude": "-17.535" },
    { "id": "QAT", "iso2code": "QA", "name": "Qatar", "capital_city": "Doha", "longitude": "51.5082", "latitude": "25.2948" },
    { "id": "ROU", "iso2code": "RO", "name": "Romania", "capital_city": "Bucharest", "longitude": "26.0979", "latitude": "44.4479" },
    { "id": "RRS", "iso2code": "R6", "name": "Resource rich Sub-Saharan Africa countries", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "RSO", "iso2code": "O6", "name": "Resource rich Sub-Saharan Africa countries, of which oil exporters", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "RUS", "iso2code": "RU", "name": "Russian Federation", "capital_city": "Moscow", "longitude": "37.6176", "latitude": "55.7558" },
    { "id": "RWA", "iso2code": "RW", "name": "Rwanda", "capital_city": "Kigali", "longitude": "30.0587", "latitude": "-1.95325" },
    { "id": "SAS", "iso2code": "8S", "name": "South Asia", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "SAU", "iso2code": "SA", "name": "Saudi Arabia", "capital_city": "Riyadh", "longitude": "46.6977", "latitude": "24.6748" },
    { "id": "SCE", "iso2code": "L7", "name": "Southern Cone", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "SDN", "iso2code": "SD", "name": "Sudan", "capital_city": "Khartoum", "longitude": "32.5363", "latitude": "15.5932" },
    { "id": "SEN", "iso2code": "SN", "name": "Senegal", "capital_city": "Dakar", "longitude": "-17.4734", "latitude": "14.7247" },
    { "id": "SGP", "iso2code": "SG", "name": "Singapore", "capital_city": "Singapore", "longitude": "103.85", "latitude": "1.28941" },
    { "id": "SLB", "iso2code": "SB", "name": "Solomon Islands", "capital_city": "Honiara", "longitude": "159.949", "latitude": "-9.42676" },
    { "id": "SLE", "iso2code": "SL", "name": "Sierra Leone", "capital_city": "Freetown", "longitude": "-13.2134", "latitude": "8.4821" },
    { "id": "SLV", "iso2code": "SV", "name": "El Salvador", "capital_city": "San Salvador", "longitude": "-89.2073", "latitude": "13.7034" },
    { "id": "SMR", "iso2code": "SM", "name": "San Marino", "capital_city": "San Marino", "longitude": "12.4486", "latitude": "43.9322" },
    { "id": "SOM", "iso2code": "SO", "name": "Somalia", "capital_city": "Mogadishu", "longitude": "45.3254", "latitude": "2.07515" },
    { "id": "SRB", "iso2code": "RS", "name": "Serbia", "capital_city": "Belgrade", "longitude": "20.4656", "latitude": "44.8024" },
    { "id": "SSA", "iso2code": "ZF", "name": "Sub-Saharan Africa (excluding high income)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "SSD", "iso2code": "SS", "name": "South Sudan", "capital_city": "Juba", "longitude": "31.6", "latitude": "4.85" },
    { "id": "SSF", "iso2code": "ZG", "name": "Sub-Saharan Africa ", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "SST", "iso2code": "S1", "name": "Small states", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "STP", "iso2code": "ST", "name": "Sao Tome and Principe", "capital_city": "Sao Tome", "longitude": "6.6071", "latitude": "0.20618" },
    { "id": "SUR", "iso2code": "SR", "name": "Suriname", "capital_city": "Paramaribo", "longitude": "-55.1679", "latitude": "5.8232" },
    { "id": "SVK", "iso2code": "SK", "name": "Slovak Republic", "capital_city": "Bratislava", "longitude": "17.1073", "latitude": "48.1484" },
    { "id": "SVN", "iso2code": "SI", "name": "Slovenia", "capital_city": "Ljubljana", "longitude": "14.5044", "latitude": "46.0546" },
    { "id": "SWE", "iso2code": "SE", "name": "Sweden", "capital_city": "Stockholm", "longitude": "18.0645", "latitude": "59.3327" },
    { "id": "SWZ", "iso2code": "SZ", "name": "Eswatini", "capital_city": "Mbabane", "longitude": "31.4659", "latitude": "-26.5225" },
    { "id": "SXM", "iso2code": "SX", "name": "Sint Maarten (Dutch part)", "capital_city": "Philipsburg", "longitude": "", "latitude": "" },
    { "id": "SXZ", "iso2code": "A4", "name": "Sub-Saharan Africa excluding South Africa", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "SYC", "iso2code": "SC", "name": "Seychelles", "capital_city": "Victoria", "longitude": "55.4466", "latitude": "-4.6309" },
    { "id": "SYR", "iso2code": "SY", "name": "Syrian Arab Republic", "capital_city": "Damascus", "longitude": "36.3119", "latitude": "33.5146" },
    { "id": "TCA", "iso2code": "TC", "name": "Turks and Caicos Islands", "capital_city": "Grand Turk", "longitude": "-71.141389", "latitude": "21.4602778" },
    { "id": "TCD", "iso2code": "TD", "name": "Chad", "capital_city": "N'Djamena", "longitude": "15.0445", "latitude": "12.1048" },
    { "id": "TEA", "iso2code": "T4", "name": "East Asia & Pacific (IDA & IBRD countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TEC", "iso2code": "T7", "name": "Europe & Central Asia (IDA & IBRD countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TGO", "iso2code": "TG", "name": "Togo", "capital_city": "Lome", "longitude": "1.2255", "latitude": "6.1228" },
    { "id": "THA", "iso2code": "TH", "name": "Thailand", "capital_city": "Bangkok", "longitude": "100.521", "latitude": "13.7308" },
    { "id": "TJK", "iso2code": "TJ", "name": "Tajikistan", "capital_city": "Dushanbe", "longitude": "68.7864", "latitude": "38.5878" },
    { "id": "TKM", "iso2code": "TM", "name": "Turkmenistan", "capital_city": "Ashgabat", "longitude": "58.3794", "latitude": "37.9509" },
    { "id": "TLA", "iso2code": "T2", "name": "Latin America & the Caribbean (IDA & IBRD countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TLS", "iso2code": "TL", "name": "Timor-Leste", "capital_city": "Dili", "longitude": "125.567", "latitude": "-8.56667" },
    { "id": "TMN", "iso2code": "T3", "name": "Middle East & North Africa (IDA & IBRD countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TON", "iso2code": "TO", "name": "Tonga", "capital_city": "Nuku'alofa", "longitude": "-175.216", "latitude": "-21.136" },
    { "id": "TSA", "iso2code": "T5", "name": "South Asia (IDA & IBRD)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TSS", "iso2code": "T6", "name": "Sub-Saharan Africa (IDA & IBRD countries)", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TTO", "iso2code": "TT", "name": "Trinidad and Tobago", "capital_city": "Port-of-Spain", "longitude": "-61.4789", "latitude": "10.6596" },
    { "id": "TUN", "iso2code": "TN", "name": "Tunisia", "capital_city": "Tunis", "longitude": "10.21", "latitude": "36.7899" },
    { "id": "TUR", "iso2code": "TR", "name": "Turkey", "capital_city": "Ankara", "longitude": "32.3606", "latitude": "39.7153" },
    { "id": "TUV", "iso2code": "TV", "name": "Tuvalu", "capital_city": "Funafuti", "longitude": "179.089567", "latitude": "-8.6314877" },
    { "id": "TWN", "iso2code": "TW", "name": "Taiwan, China", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "TZA", "iso2code": "TZ", "name": "Tanzania", "capital_city": "Dodoma", "longitude": "35.7382", "latitude": "-6.17486" },
    { "id": "UGA", "iso2code": "UG", "name": "Uganda", "capital_city": "Kampala", "longitude": "32.5729", "latitude": "0.314269" },
    { "id": "UKR", "iso2code": "UA", "name": "Ukraine", "capital_city": "Kiev", "longitude": "30.5038", "latitude": "50.4536" },
    { "id": "UMC", "iso2code": "XT", "name": "Upper middle income", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "URY", "iso2code": "UY", "name": "Uruguay", "capital_city": "Montevideo", "longitude": "-56.0675", "latitude": "-34.8941" },
    { "id": "USA", "iso2code": "US", "name": "United States", "capital_city": "Washington D.C.", "longitude": "-77.032", "latitude": "38.8895" },
    { "id": "UZB", "iso2code": "UZ", "name": "Uzbekistan", "capital_city": "Tashkent", "longitude": "69.269", "latitude": "41.3052" },
    { "id": "VCT", "iso2code": "VC", "name": "St. Vincent and the Grenadines", "capital_city": "Kingstown", "longitude": "-61.2653", "latitude": "13.2035" },
    { "id": "VEN", "iso2code": "VE", "name": "Venezuela, RB", "capital_city": "Caracas", "longitude": "-69.8371", "latitude": "9.08165" },
    { "id": "VGB", "iso2code": "VG", "name": "British Virgin Islands", "capital_city": "Road Town", "longitude": "-64.623056", "latitude": "18.431389" },
    { "id": "VIR", "iso2code": "VI", "name": "Virgin Islands (U.S.)", "capital_city": "Charlotte Amalie", "longitude": "-64.8963", "latitude": "18.3358" },
    { "id": "VNM", "iso2code": "VN", "name": "Vietnam", "capital_city": "Hanoi", "longitude": "105.825", "latitude": "21.0069" },
    { "id": "VUT", "iso2code": "VU", "name": "Vanuatu", "capital_city": "Port-Vila", "longitude": "168.321", "latitude": "-17.7404" },
    { "id": "WLD", "iso2code": "1W", "name": "World", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "WSM", "iso2code": "WS", "name": "Samoa", "capital_city": "Apia", "longitude": "-171.752", "latitude": "-13.8314" },
    { "id": "XKX", "iso2code": "XK", "name": "Kosovo", "capital_city": "Pristina", "longitude": "20.926", "latitude": "42.565" },
    { "id": "XZN", "iso2code": "A5", "name": "Sub-Saharan Africa excluding South Africa and Nigeria", "capital_city": "", "longitude": "", "latitude": "" },
    { "id": "YEM", "iso2code": "YE", "name": "Yemen, Rep.", "capital_city": "Sana'a", "longitude": "44.2075", "latitude": "15.352" },
    { "id": "ZAF", "iso2code": "ZA", "name": "South Africa", "capital_city": "Pretoria", "longitude": "28.1871", "latitude": "-25.746" },
    { "id": "ZMB", "iso2code": "ZM", "name": "Zambia", "capital_city": "Lusaka", "longitude": "28.2937", "latitude": "-15.3982" },
    { "id": "ZWE", "iso2code": "ZW", "name": "Zimbabwe", "capital_city": "Harare", "longitude": "31.0672", "latitude": "-17.8312" }
  ], 50);
};
